[package]
name = "whatsminer_chip_map"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.13", features = ["tokio"] }
tokio = { version = "1", features = ["rt-multi-thread"] }
reqwest = { version = "0.12", features = ["cookies", "rustls-tls"], default-features = false }
